name: Deploy Python application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        function_id: ${{ secrets.FUNCTION_ID }}
        runtime: 'python37'
        entrypoint: 'main.handler'
        source: './src'
        memory: '256'
        environment: DEBUG=True

