name: Deploy Python application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        coverage run -m pytest
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
    
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        function_id: ${{ secrets.FUNCTION_ID }}
        runtime: 'python37'
        entrypoint: 'main.handler'
        source: './src'
        memory: '256'
        environment: DEBUG=True
